name: CI Backend

on:
  push:
    paths:
      - 'backend/**'
      - 'docs/api/**'
      - '.github/workflows/ci-backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'docs/api/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: gert_user
          POSTGRES_PASSWORD: gert_password
          POSTGRES_DB: gert_platform
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U gert_user -d gert_platform"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10
      redis:
        image: redis:7-alpine
        ports: ['6379:6379']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install deps
        working-directory: backend
        run: npm ci

      - name: Lint OpenAPI (syntax)
        run: npm run openapi:lint
        working-directory: backend

      - name: Run migrations
        env:
          DATABASE_URL: postgres://gert_user:gert_password@localhost:5432/gert_platform
          DB_SSL_DISABLE: "1"
        run: node scripts/migrate.js
        working-directory: backend

      - name: Run tests
        env:
          NODE_ENV: test
          JWT_SECRET: devsecret
          DATABASE_URL: postgres://gert_user:gert_password@localhost:5432/gert_platform
          DB_SSL_DISABLE: "1"
        run: npm test
        working-directory: backend
